import datetime

artists_stripped_chars = ['So You Think You Can Dance', 'The String Cheese Incident', 'The String Cheese Incident', 'The String Cheese Incident', 'Top Rank Boxing Mike Alvarado vs Brandon Rios 3', 'Sam Smith', 'UFC Fight Night Brown vs Saffiedine', 'Harlem Globetrotters', '6th annual Frank Shorter RACE', 'Volbeat']

dates_culled = ['Dec 16,', 'Dec 29,', 'Dec 30,', 'Dec 31,', 'Jan 24,', 'Jan 26,', 'Feb 14,', 'Mar 7,', 'Apr 12,', 'Apr 24,']

dates_stripped_chars = ['Dec 16', 'Dec 29', 'Dec 30', 'Dec 31', 'Jan 24', 'Jan 26', 'Feb 14', 'Mar 7', 'Apr 12', 'Apr 24']

dates_format_month = ['December 16', 'December 29', 'December 30', 'December 31', 'January 24', 'January 26', 'February 14', 'March 7', 'April 12', 'April 24']

dates_format_year = ['December 16 2014', 'December 29 2014', 'December 30 2014', 'December 31 2014', 'January 24 2015', 'January 26 2015', 'February 14 2015', 'March 7 2015', 'April 12 2015', 'April 24 2015']

dates_datetime = [datetime.datetime(2014, 12, 16, 0, 0), datetime.datetime(2014, 12, 29, 0, 0), datetime.datetime(2014, 12, 30, 0, 0), datetime.datetime(2014, 12, 31, 0, 0), datetime.datetime(2015, 1, 24, 0, 0), datetime.datetime(2015, 1, 26, 0, 0), datetime.datetime(2015, 2, 14, 0, 0), datetime.datetime(2015, 3, 7, 0, 0), datetime.datetime(2015, 4, 12, 0, 0), datetime.datetime(2015, 4, 24, 0, 0)]

ticket_links_raw = ['\n\t\t\n\t\t<a href="http://www.altitudetickets.com/event/so-you-think-you-can-dance-2700/" title="Buy Tickets" target="_blank" class="btn-tickets accentBackground widgetBorderColor secondaryColor tickets status_1"><i class="fa fa-ticket fa-secondary"></i>Buy Tickets</a>\n\t', '\n\t\t\n\t\t<a href="http://www.altitudetickets.com/event/the-string-cheese-incident-3092/" title="Buy Tickets" target="_blank" class="btn-tickets accentBackground widgetBorderColor secondaryColor tickets status_1"><i class="fa fa-ticket fa-secondary"></i>Buy Tickets</a>\n\t', '\n\t\t\n\t\t<a href="http://www.altitudetickets.com/event/the-string-cheese-incident-3093/" title="Buy Tickets" target="_blank" class="btn-tickets accentBackground widgetBorderColor secondaryColor tickets status_1"><i class="fa fa-ticket fa-secondary"></i>Buy Tickets</a>\n\t', '\n\t\t\n\t\t<a href="http://www.altitudetickets.com/event/the-string-cheese-incident-3094/" title="Buy Tickets" target="_blank" class="btn-tickets accentBackground widgetBorderColor secondaryColor tickets status_1"><i class="fa fa-ticket fa-secondary"></i>Buy Tickets</a>\n\t', '\n\t\t\n\t\t<a href="http://www.altitudetickets.com/event/top-rank-boxing-mike-alvarado-vs-brandon-rios-3-3321/" title="Buy Tickets" target="_blank" class="btn-tickets accentBackground widgetBorderColor secondaryColor tickets status_1"><i class="fa fa-ticket fa-secondary"></i>Buy Tickets</a>\n\t', '\n\t\t\n\t\t<a href="http://www.altitudetickets.com/event/sam-smith-3035/" title="Buy Tickets" target="_blank" class="btn-tickets accentBackground widgetBorderColor secondaryColor tickets status_1"><i class="fa fa-ticket fa-secondary"></i>Buy Tickets</a>\n\t', '\n\t\t\n\t\t<a href="http://www.altitudetickets.com/event/ufc-fight-night-3209/" title="Buy Tickets" target="_blank" class="btn-tickets accentBackground widgetBorderColor secondaryColor tickets status_1"><i class="fa fa-ticket fa-secondary"></i>Buy Tickets</a>\n\t', '\n\t\t\n\t\t<a href="http://www.altitudetickets.com/event/harlem-globetrotters-3008/" title="Buy Tickets" target="_blank" class="btn-tickets accentBackground widgetBorderColor secondaryColor tickets status_1"><i class="fa fa-ticket fa-secondary"></i>Buy Tickets</a>\n\t', '\n\t\t\n\t\t<a href="http://www.runningguru.com/EventInformation.asp?SourceCode=Search&amp;eID=12791" title="Buy Tickets" target="_blank" class="btn-tickets accentBackground widgetBorderColor secondaryColor tickets status_1"><i class="fa fa-ticket fa-secondary"></i>Buy Tickets</a>\n\t', '\n\t\t\n\t\t<a href="http://www.altitudetickets.com/event/volbeat-3153/" title="Buy Tickets" target="_blank" class="btn-tickets accentBackground widgetBorderColor secondaryColor tickets status_1"><i class="fa fa-ticket fa-secondary"></i>Buy Tickets</a>\n\t']

ticket_links = ['http://www.altitudetickets.com/event/so-you-think-you-can-dance-2700/', 'http://www.altitudetickets.com/event/the-string-cheese-incident-3092/', 'http://www.altitudetickets.com/event/the-string-cheese-incident-3093/', 'http://www.altitudetickets.com/event/the-string-cheese-incident-3094/', 'http://www.altitudetickets.com/event/top-rank-boxing-mike-alvarado-vs-brandon-rios-3-3321/', 'http://www.altitudetickets.com/event/sam-smith-3035/', 'http://www.altitudetickets.com/event/ufc-fight-night-3209/', 'http://www.altitudetickets.com/event/harlem-globetrotters-3008/', 'http://www.runningguru.com/EventInformation.asp?SourceCode=Search&amp;eID=12791', 'http://www.altitudetickets.com/event/volbeat-3153/']