import datetime

artists_stripped_html = ['Iggy Azalea', 'Fleetwood Mac: On With The Show', 'WWE Monday Night Raw', 'Enrique Iglesias & Pitbull', 'ERIC CHURCH “THE OUTSIDERS WORLD TOUR”', 'New Seats!', 'Monster Jam 2015', 'Neil Diamond World Tour 2015', 'Harlem Globetrotters', 'Bette Midler', 'DISNEY ON ICE: Frozen', 'Taylor Swift Announces The 1989 World Tour', "Jammin' 101.5 Super Freestyle Explosion"]

artists_format_special = ['Iggy Azalea', 'Fleetwood Mac', 'WWE Monday Night Raw', 'Enrique Iglesias & Pitbull', 'ERIC CHURCH “THE OUTSIDERS WORLD TOUR”', 'New Seats!', 'Monster Jam 2015', 'Neil Diamond World Tour 2015', 'Harlem Globetrotters', 'Bette Midler', 'DISNEY ON ICE', 'Taylor Swift Announces The 1989 World Tour', "Jammin' 101.5 Super Freestyle Explosion"]

dates_stripped_html = ['April 27, 2015 at 7:30 PM', 'Wednesday, April 1 at 8:00pm', 'Monday, February 2 at 5:30pm', 'Tuesday, February 17 at 7:30 PM ', 'Tuesday, January 27 ', 'Watch how we pull off the largest in-house', 'February 6-8, 2015 ', 'Sunday, May 31 at 8PM', 'Saturday, March 7 at 1pm', 'May 20, 2015', '10 Shows December 3 - 6, 2015', 'September 5 & 6, 2015', 'Saturday, June 27 at 7:30pm']

dates_format_special = ['April 27, 2015 at 7:30 PM', 'Wednesday, April 1 at 8:00pm', 'Monday, February 2 at 5:30pm', 'Tuesday, February 17 at 7:30 PM ', 'Tuesday, January 27 ', 'February 6-8, 2015 ', 'Sunday, May 31 at 8PM', 'Saturday, March 7 at 1pm', 'May 20, 2015', '10 Shows December 3 - 6, 2015', 'September 5 & 6, 2015', 'Saturday, June 27 at 7:30pm']

dates_culled = ['April 27,', 'April 1', 'February 2', 'February 17', 'January 27', 'February 6', 'May 31', 'March 7', 'May 20,', 'December 3', 'September 5', 'June 27']

dates_stripped_chars = ['April 27', 'April 1', 'February 2', 'February 17', 'January 27', 'February 6', 'May 31', 'March 7', 'May 20', 'December 3', 'September 5', 'June 27']

dates_format_year = ['April 27 2015', 'April 1 2015', 'February 2 2015', 'February 17 2015', 'January 27 2015', 'February 6 2015', 'May 31 2015', 'March 7 2015', 'May 20 2015', 'December 3 2014', 'September 5 2015', 'June 27 2015']

dates_datetime = [datetime.datetime(2015, 4, 27, 0, 0), datetime.datetime(2015, 4, 1, 0, 0), datetime.datetime(2015, 2, 2, 0, 0), datetime.datetime(2015, 2, 17, 0, 0), datetime.datetime(2015, 1, 27, 0, 0), datetime.datetime(2015, 2, 6, 0, 0), datetime.datetime(2015, 5, 31, 0, 0), datetime.datetime(2015, 3, 7, 0, 0), datetime.datetime(2015, 5, 20, 0, 0), None, datetime.datetime(2015, 9, 5, 0, 0), datetime.datetime(2015, 6, 27, 0, 0)]

ticket_links = ['http://www.altitudetickets.com/event/iggy-azalea-the-great-escape-tour-3277/', 'http://www.altitudetickets.com/event/fleetwood-mac-on-with-the-show-3122/', 'http://www.altitudetickets.com/event/fleetwood-mac-on-with-the-show-3122/', 'http://www.altitudetickets.com/event/wwe-monday-night-raw-3273/', 'http://www.altitudetickets.com/event/enrique-iglesias-pitbull-3165/', 'http://www.altitudetickets.com/event/eric-church-the-outsiders-world-tour-3146/', 'http://www.pepsicenter.com/seat-upgrades/', 'http://www.altitudetickets.com/event-groups/monster-jam-2015/', 'http://www.altitudetickets.com/event/harlem-globetrotters-3010/', 'http://www.altitudetickets.com/event/bette-midler-3195/', 'http://www.altitudetickets.com/event-groups/disney-on-ice-frozen/', 'http://www.altitudetickets.com/event-groups/disney-on-ice-frozen/', 'http://www.altitudetickets.com/event/super-freestyle-explosion-3233/', 'http://www.altitudetickets.com/event/super-freestyle-explosion-3233/']

ticket_links_patched = ['http://www.altitudetickets.com/event/iggy-azalea-the-great-escape-tour-3277/', 'http://www.altitudetickets.com/event/fleetwood-mac-on-with-the-show-3122/', 'http://www.altitudetickets.com/event/fleetwood-mac-on-with-the-show-3122/', 'http://www.altitudetickets.com/event/wwe-monday-night-raw-3273/', 'http://www.altitudetickets.com/event/enrique-iglesias-pitbull-3165/', 'http://www.altitudetickets.com/event/eric-church-the-outsiders-world-tour-3146/', 'http://www.pepsicenter.com/seat-upgrades/', 'http://www.altitudetickets.com/event-groups/monster-jam-2015/', 'http://www.altitudetickets.com/event/harlem-globetrotters-3010/', 'http://www.altitudetickets.com/event/bette-midler-3195/', 'http://www.altitudetickets.com/event-groups/disney-on-ice-frozen/', 'http://www.altitudetickets.com/event-groups/disney-on-ice-frozen/', 'http://www.altitudetickets.com/event/super-freestyle-explosion-3233/', 'http://www.altitudetickets.com/event/super-freestyle-explosion-3233/']